---
apiVersion: v1
kind: Service
metadata:
  labels:
    project: piggymetrics
    tier: middleware
    app: config
  name: config
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8888
      targetPort: 8888
  selector:
    project: piggymetrics
    tier: middleware
    app: config
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    project: piggymetrics
    tier: middleware
    app: config
  name: config
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
        app: config    
  template:
    metadata:
      labels:
        project: piggymetrics
        tier: middleware
        app: config
    spec:
      containers:
        - env:
            - name: CONFIG_SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: piggymetrics
                  key: config_service_password
          image: ${CONTAINER_REGISTRY}.azurecr.io/piggymetrics-config:dev
          name: config
          ports:
            - containerPort: 8888
          resources: {}
      restartPolicy: Always
status: {}
